#ifndef __REAL_TO_SIM_CONTROL_BOARD_LOG_COMPONENT_HPP__
#define __REAL_TO_SIM_CONTROL_BOARD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(R2SCB)

#endif // __REAL_TO_SIM_CONTROL_BOARD_LOG_COMPONENT_HPP__
