#ifndef __PLAYBACK_THREAD_LOG_COMPONENT_HPP__
#define __PLAYBACK_THREAD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(PBT)

#endif // __PLAYBACK_THREAD_LOG_COMPONENT_HPP__
