/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Oct  3 12:02:21 2025


#include "BasicJointCoupling_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(BasicJointCouplingParamsCOMPONENT, "yarp.device.BasicJointCoupling")
}


BasicJointCoupling_ParamsParser::BasicJointCoupling_ParamsParser()
{
}


std::vector<std::string> BasicJointCoupling_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("actuatedAxes");
    params.push_back("physicalJoints");
    return params;
}


bool      BasicJointCoupling_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(BasicJointCouplingParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter actuatedAxes
    {
        if (config.check("actuatedAxes"))
        {
            {
                m_actuatedAxes.clear();
                yarp::os::Bottle* tempBot = config.find("actuatedAxes").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_actuatedAxes.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(BasicJointCouplingParamsCOMPONENT) <<"parameter 'actuatedAxes' is not a properly formatted bottle";
                }
            }
            yCInfo(BasicJointCouplingParamsCOMPONENT) << "Parameter 'actuatedAxes' using value:" << m_actuatedAxes;
        }
        else
        {
            yCError(BasicJointCouplingParamsCOMPONENT) << "Mandatory parameter 'actuatedAxes' not found!";
            yCError(BasicJointCouplingParamsCOMPONENT) << "Description of the parameter: list of actuated axes names";
            return false;
        }
        prop_check.unput("actuatedAxes");
    }

    //Parser of parameter physicalJoints
    {
        if (config.check("physicalJoints"))
        {
            {
                m_physicalJoints.clear();
                yarp::os::Bottle* tempBot = config.find("physicalJoints").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_physicalJoints.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(BasicJointCouplingParamsCOMPONENT) <<"parameter 'physicalJoints' is not a properly formatted bottle";
                }
            }
            yCInfo(BasicJointCouplingParamsCOMPONENT) << "Parameter 'physicalJoints' using value:" << m_physicalJoints;
        }
        else
        {
            yCError(BasicJointCouplingParamsCOMPONENT) << "Mandatory parameter 'physicalJoints' not found!";
            yCError(BasicJointCouplingParamsCOMPONENT) << "Description of the parameter: list of physical joints names";
            return false;
        }
        prop_check.unput("physicalJoints");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(BasicJointCouplingParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(BasicJointCouplingParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      BasicJointCoupling_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: BasicJointCoupling\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'actuatedAxes': list of actuated axes names\n");
    doc = doc + std::string("'physicalJoints': list of physical joints names\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device BasicJointCoupling --actuatedAxes <mandatory_value> --physicalJoints <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device BasicJointCoupling --actuatedAxes <mandatory_value> --physicalJoints <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
