#ifndef __BASIC_JOINT_COUPLING_LOG_COMPONENT_HPP__
#define __BASIC_JOINT_COUPLING_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(BJC)

#endif // __BASIC_JOINT_COUPLING_LOG_COMPONENT_HPP__
